name: Deploy static site to Azure Web App

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: Kawaseee

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write deployment version file
        run: |
          if [ -d src ]; then
            printf '{"version": "%s"}\n' "${GITHUB_SHA}" > src/version.json
          else
            printf '{"version": "%s"}\n' "${GITHUB_SHA}" > version.json
          fi
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: <publishData><publishProfile profileName="Kawaseee - Web Deploy" publishMethod="MSDeploy" publishUrl="kawaseee-h5bffxeea4f8enbj.scm.japaneast-01.azurewebsites.net:443" msdeploySite="Kawaseee" userName="$Kawaseee" userPWD="anzcB2tvDkYNJJXomYZ1wxMSZ4iq00jhppWBShMiEv3wmKCRKaXqyK5Lvfu7" destinationAppUrl="https://kawaseee-h5bffxeea4f8enbj.japaneast-01.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="Kawaseee - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-ty1-043.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="Kawaseee\$Kawaseee" userPWD="anzcB2tvDkYNJJXomYZ1wxMSZ4iq00jhppWBShMiEv3wmKCRKaXqyK5Lvfu7" destinationAppUrl="https://kawaseee-h5bffxeea4f8enbj.japaneast-01.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="Kawaseee - Zip Deploy" publishMethod="ZipDeploy" publishUrl="kawaseee-h5bffxeea4f8enbj.scm.japaneast-01.azurewebsites.net:443" userName="$Kawaseee" userPWD="anzcB2tvDkYNJJXomYZ1wxMSZ4iq00jhppWBShMiEv3wmKCRKaXqyK5Lvfu7" destinationAppUrl="https://kawaseee-h5bffxeea4f8enbj.japaneast-01.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="Kawaseee - ReadOnly - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-ty1-043dr.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="Kawaseee\$Kawaseee" userPWD="anzcB2tvDkYNJJXomYZ1wxMSZ4iq00jhppWBShMiEv3wmKCRKaXqyK5Lvfu7" destinationAppUrl="https://kawaseee-h5bffxeea4f8enbj.japaneast-01.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>
          package: .
